//生物掉落JER覆盖(有独立战利品池)
LootJS.lootTables(event => {
  event.getLootTable("minecraft:entities/zombie")
    .firstPool()
    .addEntry('minecraft:flint')
    .addEntry('minecraft:iron_nugget')
    .addEntry('minecraft:gold_nugget')
    .addEntry('minecraft:rotten_flesh')
    .addEntry('endersequipment:putrid_flesh');
    event.getLootTable("minecraft:entities/skeleton")
    .firstPool()
    .addEntry('endersequipment:rotten_bone')
    .addEntry('minecraft:gold_nugget')
    .addEntry('minecraft:iron_nugget')
    .addEntry('minecraft:bone');
  event.getLootTable("minecraft:entities/creeper")
    .firstPool()
     .addEntry('hazennstuff:chlorophyte_chunk')
    .addEntry('minecraft:gunpowder')
    .addEntry('minecraft:tnt')
    .addEntry('minecraft:redstone');
  event.getLootTable("minecraft:entities/spider")
    .firstPool()
     .addEntry('malum:raw_brilliance')
    .addEntry('hazennstuff:spider_fang')
    .addEntry('minecraft:raw_iron')
    .addEntry('minecraft:string');
  event.getLootTable("minecraft:entities/cave_spider")
    .firstPool()
      .addEntry('malum:raw_brilliance')
    .addEntry('hazennstuff:spider_fang')
    .addEntry('minecraft:raw_iron')
    .addEntry('minecraft:string');
  event.getLootTable("minecraft:entities/enderman")
    .firstPool()
    .addEntry('minecraft:ender_eye')
    .addEntry('locusazzurro_icaruswings:void_essence')
    .addEntry('minecraft:ender_pearl')
    .addEntry('malum:alchemical_calx');
  event.getLootTable("minecraft:entities/phantom")
    .firstPool()
    .addEntry('minecraft:phantom_membrane')
    .addEntry('locusazzurro_icaruswings:zephir_essence')
    .addEntry('minecraft:feather')
    .addEntry('malum:alchemical_calx');
    event.getLootTable("minecraft:entities/magma_cube")
    .firstPool()
    .addEntry('locusazzurro_icaruswings:nether_essence')
});